name: My Workflow

on:
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [x86_64]

    steps:
      - name: Check Architecture
        run: |
          if [[ "${{ matrix.architecture }}" != "x86_64" ]]; then
            echo "Unsupported architecture. Exiting..."
            exit 1
          fi
