name: Compile and Build

# run on push
on:
  push:
    branches: [ master ]

jobs:
  my_job:
    name: Compile and build using SDK
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [x86_64]

    steps:
      - uses: actions/checkout@v2

      - name: Check Architecture
        run: |
          if [[ "${{ matrix.architecture }}" != "x86_64" ]]; then
            echo "Unsupported architecture. Exiting..."
            exit 1
          fi

      - name: download sdk
        run: wget https://updates.victronenergy.com/feeds/venus/release/sdk/venus-dunfell-x86_64-arm-cortexa8hf-neon-toolchain-v3.13.sh

      - name: change SDK permissions
        run: chmod u+x venus-dunfell-x86_64-arm-cortexa8hf-neon-toolchain-v3.13.sh
      
      - name: install sdk
        run: sudo ./venus-dunfell-x86_64-arm-cortexa8hf-neon-toolchain-v3.13.sh -y
      
      - name: create current directory
        run: mkdir -p /opt/venus/current

      - name: symlinks
        run: sudo ln -s /opt/venus/dunfell-arm-cortexa8hf-neon/* /opt/venus/current/

      - name: list the contents of the current directory
        run: sudo ls -la /opt/venus/current

      - name: use sdk
        run: . /opt/venus/current/environment-setup-cortexa8hf-neon-ve-linux-gnueabi

      - name: Run qmake
        run: |
          export QMAKESPEC=/opt/venus/current/sysroots/x86_64-ve-linux/usr/mkspecs/linux-g++
          /opt/venus/current/sysroots/x86_64-ve-linux/usr/bin/qmake dbus_modbustcp.pro

      - name: build project
        run: ./build.sh

      # list the contents of build/dbus-modbustcp
      - name: list the contents of build/dbus-modbustcp
        run: ls -la build/dbus-modbustcp
